### ISSUE TITLE
Version  6.0.1 typescript not job

### ISSUE THREAD

**Issue by Blynskyniki** [johnbrett/hapi-auth-bearer-token#148]
Helllo. I am using hapi and typescript . Version 6.0.1 not job. Error impossible to find register of undefinded

**Comment by Blynskyniki** [comment]
Version 5.0.0 functions normally

**Comment by johnbrett** [comment]
ok, I will need an example to reproduce this to debug. Can you create a project where this is failing with version 6.0.1 but works with version 5.0.0?

**Comment by johnbrett** [comment]
I'm guessing the issue here is you're using v6 of this module with a hapi version 16 or below, this is documented in the release notes: https://github.com/johnbrett/hapi-auth-bearer-token/issues/146.  I'm going to close this unless you can provide more information about versions or a project where this is failing.
